services:
  securecapitajet:
    container_name: secureappback
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: secureappback:v1
    restart: unless-stopped
    env_file:
      - ./.env.prod
    expose:
      - ${CONTAINER_PORT}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}
networks:
  internalnet:
    driver: bridge