jwt:
  secret: ENC(7/UD9PritIRE5Ce06dsmUXxAMavF0ZpXmJ1nsh600dznc6rO5nt6JA==)
server:
  port: 8085
  error:
    path: /user/error
    whitelabel:
      enabled: false
spring:
  application:
    name: secureappback
  datasource:
    url: jdbc:postgresql://localhost:5432/secureCapita
    username: ENC(nnBADRj6fvYT/TJ3MyzKQVyqDVYDhAiQ)
    password: ENC(EGJMxU6bmZMWFMcoituqdg==)
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false

