#DATABASE CONFIG
DB_PROVIDER: postgresql
DB_HOST: localhost
DB_PORT: 5433
DB_NAME: secureCapita
DB_USERNAME: ENC(nnBADRj6fvYT/TJ3MyzKQVyqDVYDhAiQ)
DB_PASSWORD: ENC(EGJMxU6bmZMWFMcoituqdg==)
DB_DRIVER: ENC(bV+z0uaUhtLQ7gEFN83UPZbqZGysKhwgNdVkEYF5Z9Q=)
DDL_AUTO: update

#SERVER CONFIG
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#EMAIL CONFIG
EMAIL_SMTP_PORT: ENC(lczYTK/GlJ89bESnOBhxUg==)
EMAIL_SMTP_HOST: ENC(NUV5AjIAiuLp1kwf/PJatGrAnUtnqTQtKPvsRm4zbNI=)
EMAIL_USERNAME: ENC(WXSieszJBlhSCgHlPHjfYNt5HmY4ysLf2D+0ImTmpSw=)
EMAIL_PASSWORD: ENC(qW/ppbUomLX3gn6o11mH+KdGjK09kmeb)
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200

#JWT CONFIG
JWT_SECRET: ENC(42PAk0avAHEtYIaFF8kbbDgYKqomgNxrXlgAOjlApvKmT/tww3EddA==)
JWT_ACCESS_TIME: 432_000_000
JWT_REFRESH_TIME: 432_000_000